import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "da";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.about": "About",
    "nav.products": "Products",
    "nav.applications": "Applications",
    "nav.cargo": "Cargo",
    "nav.blog": "CARGO INTELLIGENCE",
    "nav.contact": "Contact",
    "nav.resources": "Resources",
    "nav.getQuote": "Get quote",
    "nav.faq": "FAQ",
    "nav.viewAllProducts": "View all products",
    "nav.desiccants": "Desiccants",
    "nav.cargoProtection": "Cargo protection",
    "nav.otherProducts": "Other products",
    
    // Products
    "products.drybagI": "DRY-BAG I",
    "products.drybagIII": "DRY-BAG III",
    "products.silica": "Silica gel",
    "products.dunnage": "Dunnage bags",
    "products.molecular": "Molecular sieve",
    "products.calcium": "Calcium chloride",
    "products.retail": "Retail products",
    "products.edge": "Edge protectors",
    "products.antiSlip": "Anti-slip sheets",
    "products.stabustrap": "Stabustrap",
    "products.datalogger": "Datalogger",
    
    // Footer
    "footer.company": "Company",
    "footer.resources": "Resources",
    "footer.downloads": "Downloads",
    "footer.technicalSpecs": "Technical specs",
    "footer.caseStudies": "Case studies",
    "footer.aboutUs": "About us",
    "footer.industries": "Industries",
    "footer.privacy": "Privacy policy",
    "footer.terms": "Terms of service",
    "footer.rights": "All rights reserved.",
    "footer.tagline": "Leading Danish manufacturer of high-quality desiccants, protecting cargo worldwide since 1979.",
    
    // Top bar
    "topbar.message": "Danish engineering since 1979 | Global shipping available",

    // Hero Section
    "hero.badge": "Industry-leading protection",
    "hero.title1": "YOUR PARTNER IN",
    "hero.title2": "MOISTURE CONTROL",
    "hero.title3": "& CARGO SAFETY",
    "hero.description": "Discover our innovative and sustainable solutions for protecting your goods from moisture damage and ensuring stable transport worldwide.",
    "hero.exploreProducts": "Explore products",
    "hero.contactUs": "Contact us",
    "hero.yearsExperience": "Years experience",
    "hero.countriesServed": "Countries served",
    "hero.globalSupport": "Global support",

    // About Section
    "about.badge": "About DRY-BAG",
    "about.title1": "Leading Danish manufacturer of",
    "about.title2": "high-quality desiccants",
    "about.description": "DRY-BAG is a leading Danish manufacturer of high-quality desiccants, specifically engineered to safeguard your goods during transit for both export and e-commerce. We understand the critical need to protect products from moisture damage, ensuring they arrive at their destination in perfect condition, every time.",
    "about.feature1.title": "Located in Denmark",
    "about.feature1.desc": "Headquartered in the heart of Scandinavian innovation",
    "about.feature2.title": "Since 1979",
    "about.feature2.desc": "Over four decades of moisture control expertise",
    "about.feature3.title": "Eco-friendly production",
    "about.feature3.desc": "Sustainable practices for a greener future",
    "about.feature4.title": "Tailored solutions",
    "about.feature4.desc": "Custom-engineered for your specific needs",
    "about.yearsExcellence": "Years of excellence",
    "about.protectingCargo": "Protecting cargo worldwide",

    // Products Section
    "products.badge": "Featured products",
    "products.title1": "Industrial-grade",
    "products.title2": "protection solutions",
    "products.description": "Explore our range of innovative solutions designed to protect your goods and optimize your logistics operations.",
    "products.viewAll": "View all products",
    "products.learnMore": "Learn more",
    "products.dunnageBag.subtitle": "Kraft paper & PP woven",
    "products.dunnageBag.desc": "Industrial air bags for cargo stabilization during transport",
    "products.drybagI.subtitle": "Original formula",
    "products.drybagI.desc": "Clay-based desiccant engineered for long ocean journeys",
    "products.silicaGel.subtitle": "E-commerce ready",
    "products.silicaGel.desc": "Premium silica gel packets for in-box moisture protection",
    "products.drybagIII.subtitle": "Bentonite clay",
    "products.drybagIII.desc": "Industrial-grade desiccant available in multiple sizes",

    // Industries Section
    "industries.badge": "Applications",
    "industries.title1": "Tailored solutions for",
    "industries.title2": "every industry",
    "industries.description": "Discover how our moisture control solutions protect critical assets across diverse industries worldwide.",
    "industries.wind.title": "Wind energy",
    "industries.wind.desc": "Desiccants prevent moisture from corroding critical components within wind turbines, such as gearboxes and generators. By maintaining a dry internal environment, they extend lifespan and ensure reliable operation.",
    "industries.metals.title": "Metals industry",
    "industries.metals.desc": "Protect steel coils, aluminum sheets, and precision metal components from rust and oxidation during shipping. Our solutions ensure metals arrive in pristine condition.",
    "industries.food.title": "Food & feed",
    "industries.food.desc": "Safeguard food ingredients and animal feed from moisture-induced spoilage. Our food-safe desiccants maintain product quality throughout the supply chain.",
    "industries.pharma.title": "Pharmaceuticals",
    "industries.pharma.desc": "Pharmaceutical-grade molecular sieve desiccants ensure medication stability and efficacy. Meet stringent regulatory requirements with our certified solutions.",

    // Contact Section
    "contact.badge": "Get in touch",
    "contact.title1": "Let's protect your",
    "contact.title2": "cargo together",
    "contact.description": "Have questions about moisture control or cargo safety? Our team is ready to help. Whether you need a quote, technical specifications, or guidance on the right desiccant for your shipment, we'll respond within 24 hours.",
    "contact.whyPartner": "Why partner with DRY-BAG?",
    "contact.benefit1": "40+ years of industry expertise",
    "contact.benefit2": "Tailored solutions for your unique needs",
    "contact.benefit3": "Global shipping with local support",
    "contact.benefit4": "24-hour response guarantee",
    "contact.headquarters": "Denmark (Headquarters)",
    "contact.whatsapp": "WhatsApp available",
    "contact.form.fullName": "Full name",
    "contact.form.email": "Email address",
    "contact.form.company": "Company name",
    "contact.form.message": "Message",
    "contact.form.placeholder.name": "John Doe",
    "contact.form.placeholder.email": "john@company.com",
    "contact.form.placeholder.company": "Your Company Ltd.",
    "contact.form.placeholder.message": "Tell us about your moisture control needs...",
    "contact.form.submit": "Send message",

    // About Page
    "aboutPage.badge": "About us",
    "aboutPage.title1": "Our job is to make",
    "aboutPage.title2": "your job easier.",
    "aboutPage.description": "That means making sure your products arrive in perfect condition. With four decades of experience, we've learned that every shipment has its own challenges.",
    "aboutPage.decadesTitle": "Four decades of expertise",
    "aboutPage.decadesDesc1": "Our mission, since 1979, has been to reliably and responsibly protect products from moisture. We offer custom moisture control solutions designed to safeguard your goods, focusing on long-term performance and sustainability.",
    "aboutPage.decadesDesc2": "As a manufacturer with in-house production, we have direct control over the entire process. This allows us to ensure every product meets our rigorous quality standards while providing you with the most competitive prices on the market.",
    "aboutPage.value1.title": "Sustainable solutions",
    "aboutPage.value1.desc": "Our products are designed with environmental stewardship in mind. We use eco-friendly materials and sustainable processes to deliver effective moisture control without compromising your company's green initiatives.",
    "aboutPage.value2.title": "Innovative technology",
    "aboutPage.value2.desc": "We leverage cutting-edge technology and continuous research to develop solutions that are at the forefront of the industry. Our commitment to innovation ensures your products are protected by the most advanced moisture control available.",
    "aboutPage.value3.title": "Guaranteed product integrity",
    "aboutPage.value3.desc": "With over four decades of experience, we know how to safeguard your goods. We provide reliable, customized solutions that consistently exceed expectations, giving you peace of mind that your products will arrive in perfect condition.",
    "aboutPage.offerTitle": "What we offer you",
    "aboutPage.offer1.title": "Custom-engineered solutions",
    "aboutPage.offer1.desc": "We start by understanding your unique challenges to build a moisture control strategy that works specifically for you. This means less wasted product and more peace of mind.",
    "aboutPage.offer2.title": "Proven performance",
    "aboutPage.offer2.desc": "Our products are backed by over 40 years of expertise and a commitment to quality. You can trust that our solutions will perform reliably, protecting your goods and your bottom line.",
    "aboutPage.offer3.title": "Long-term sustainability",
    "aboutPage.offer3.desc": "We're dedicated to responsible and sustainable practices. Our solutions are designed for efficiency and long-term performance, helping you reduce waste and minimize your environmental impact.",
    "aboutPage.offer4.title": "Expert support",
    "aboutPage.offer4.desc": "We're more than just a provider; we're your partner. Our team of experts is here to provide guidance and support every step of the way, ensuring your products are protected no matter where they go.",
    "aboutPage.statsTitle": "Our impact in numbers",
    "aboutPage.stat1": "years protecting cargo globally",
    "aboutPage.stat2": "satisfied customers since 1979",
    "aboutPage.stat3": "countries where we safeguard cargo",
    "aboutPage.ctaTitle": "Ready to learn more?",
    "aboutPage.ctaDesc": "We're always happy to discuss how Dry-Bag can meet your specific needs. Reach out to our team today.",
    "aboutPage.ctaButton": "Contact our experts",

    // Contact Page
    "contactPage.badge": "Contact us",
    "contactPage.title1": "Get in touch",
    "contactPage.title2": "with Dry-Bag",
    "contactPage.description": "We are ready to serve your business by helping you protect your cargo. Don't hesitate to get in touch—we're looking forward to hearing from you.",
    "contactPage.formTitle": "Send us a message",
    "contactPage.form.name": "Name",
    "contactPage.form.namePlaceholder": "Your name",
    "contactPage.form.emailPlaceholder": "your@email.com",
    "contactPage.form.messagePlaceholder": "How can we help you?",
    "contactPage.form.sending": "Sending...",
    "contactPage.alternativeTitle": "Alternative ways to connect",
    "contactPage.email": "Email",
    "contactPage.phone": "Phone",
    "contactPage.address": "Address",
    "contactPage.hours": "Business hours",
    "contactPage.hoursValue": "Mon-Fri: 8:00 AM - 3:00 PM (CET)",
    "contactPage.followUs": "Follow us",
    "contactPage.distributorTitle": "Become a distributor",
    "contactPage.distributorDesc": "DRY-BAG® is distributed via our partners globally. If you have any questions, or want to become a distributor, feel free to contact us.",
    "contactPage.messageSent": "Message sent!",
    "contactPage.messageConfirm": "We'll get back to you as soon as possible.",

    // Applications Page
    "applicationsPage.badge": "Industry solutions",
    "applicationsPage.title1": "Moisture protection",
    "applicationsPage.title2": "for every industry",
    "applicationsPage.description": "Discover how our industrial desiccants provide critical protection against moisture damage, corrosion, and spoilage across a wide range of sectors.",
    "applicationsPage.gridTitle": "Industries we serve",
    "applicationsPage.gridDesc": "Our moisture control solutions are trusted across diverse industries worldwide.",
    "applicationsPage.pharmaceutical.title": "Pharmaceutical",
    "applicationsPage.pharmaceutical.desc": "Moisture can degrade active ingredients and shorten shelf life. Our desiccants protect the chemical integrity and efficacy of drugs, tablets, and powders.",
    "applicationsPage.electronics.title": "Electronics & semiconductors",
    "applicationsPage.electronics.desc": "Moisture is a leading cause of corrosion and short circuits. Our desiccants safeguard sensitive components like circuit boards and microchips during storage and transit.",
    "applicationsPage.food.title": "Food & beverage",
    "applicationsPage.food.desc": "Prevent clumping, spoilage, and microbial growth in dry foods. Our food-grade desiccants maintain freshness and extend the shelf life of your products.",
    "applicationsPage.logistics.title": "Logistics & shipping",
    "applicationsPage.logistics.desc": "Protect cargo from \"container rain\" and moisture damage during global transport. Our desiccants ensure goods arrive in pristine condition, regardless of climate changes.",
    "applicationsPage.automotive.title": "Automotive",
    "applicationsPage.automotive.desc": "Prevent corrosion and malfunction in sensitive automotive electronics and precision metal parts. Our solutions keep components dry during storage and transport.",
    "applicationsPage.defense.title": "Defense & military",
    "applicationsPage.defense.desc": "Ensure mission-critical equipment, including weapons, optics, and electronics, remains dry and functional for long-term storage and use in harsh environments.",
    "applicationsPage.chemical.title": "Chemical & petrochemical",
    "applicationsPage.chemical.desc": "Crucial for removing water from industrial gas streams and protecting moisture-sensitive chemical substances during processing and storage.",
    "applicationsPage.textile.title": "Textile & leather",
    "applicationsPage.textile.desc": "Prevent mold, mildew, and discoloration on clothing, footwear, and leather goods. Our desiccants maintain product quality, especially during long-term storage and shipping.",
    "applicationsPage.metal.title": "Metal processing",
    "applicationsPage.metal.desc": "Combat rust and corrosion on metal parts, tools, and machinery. Our desiccants provide a protective environment for components during storage and shipping.",
    "applicationsPage.ctaTitle": "Find your solution",
    "applicationsPage.ctaDesc": "Not sure which product is right for your industry? Our experts can help you assess your requirements and recommend the most effective solution.",
    "applicationsPage.viewProducts": "View products",
    "applicationsPage.contactExperts": "Contact experts",

    // FAQ Page
    "faqPage.badge": "Support",
    "faqPage.title1": "Frequently asked",
    "faqPage.title2": "questions",
    "faqPage.description": "Find answers to common questions about our desiccants, applications, and services.",
    "faqPage.q1": "What is a desiccant and how does it work?",
    "faqPage.a1": "A desiccant is a hygroscopic substance that induces or sustains a state of dryness in its vicinity. It absorbs water molecules from the surrounding air, effectively reducing humidity levels. Our desiccants use materials like silica gel, clay (Moclay), and calcium chloride to protect products from moisture damage during storage and shipping.",
    "faqPage.q2": "Which desiccant is right for my application?",
    "faqPage.a2": "The right desiccant depends on several factors: the type of goods being protected, humidity levels, duration of protection needed, and regulatory requirements. Silica gel is ideal for pharmaceuticals and electronics. Clay-based products like DRY-BAG I and III are excellent for container shipping. Calcium chloride is best for heavy-duty, long-haul ocean freight. Contact our experts for personalized recommendations.",
    "faqPage.q3": "How much desiccant do I need for my container?",
    "faqPage.a3": "The amount of desiccant needed depends on the container size, contents, expected transit time, and climate conditions. As a general rule, for a 20ft container, you might need 8-12 units of DRY-BAG for standard shipments. For high-humidity routes or sensitive cargo, more may be required. Our team can help calculate the exact requirements for your specific situation.",
    "faqPage.q4": "Are your desiccants safe for use with food products?",
    "faqPage.a4": "Yes, our silica gel and clay-based desiccants (DRY-BAG I and III) are made with FDA-approved materials and are safe for use in food-adjacent applications. They are non-toxic and chemically inert. However, they should not be consumed. For specific food safety certifications, please contact us.",
    "faqPage.q5": "Can desiccants be regenerated and reused?",
    "faqPage.a5": "Some of our desiccants can be regenerated. DRY BAG Retail is specifically designed to be regenerable—simply dry the contents in an oven to restore absorption capacity. Silica gel can also be regenerated in some cases. Clay-based shipping desiccants are typically single-use due to their heavy-duty nature.",
    "faqPage.q6": "What is 'container rain' and how do desiccants prevent it?",
    "faqPage.a6": "Container rain occurs when temperature fluctuations during shipping cause moisture in the air inside a container to condense on the container walls and ceiling, then drip onto cargo. This can cause mold, corrosion, and water damage. Desiccants absorb excess moisture from the air, preventing condensation from forming.",
    "faqPage.q7": "How should desiccants be stored before use?",
    "faqPage.a7": "Desiccants should be stored in their original, sealed packaging until ready for use. Keep them in a cool, dry place away from direct sunlight. Once the packaging is opened, unused desiccants should be resealed in airtight containers or bags to prevent premature moisture absorption.",
    "faqPage.q8": "Do you offer custom sizes or formulations?",
    "faqPage.a8": "Yes, we offer custom solutions for specific applications. Whether you need particular sizes, packaging types, or absorption capacities, our team can work with you to develop a tailored moisture control solution. Contact us to discuss your requirements.",
    "faqPage.q9": "What shipping options are available?",
    "faqPage.a9": "We ship globally and offer various shipping options depending on order size and urgency. Standard freight, express shipping, and bulk container loads are all available. Contact our sales team for specific shipping quotes and lead times.",
    "faqPage.q10": "How can I become a distributor?",
    "faqPage.a10": "We welcome partnership inquiries from potential distributors worldwide. If you're interested in becoming a DRY-BAG distributor, please contact us with information about your company, market area, and experience in the moisture control or packaging industry.",
    "faqPage.ctaTitle": "Still have questions?",
    "faqPage.ctaDesc": "Can't find what you're looking for? Our team is here to help with any questions about our products or services.",
    "faqPage.ctaButton": "Contact us",

    // Blog Page
    "blogPage.badge": "Technical knowledge hub",
    "blogPage.title1": "Cargo",
    "blogPage.title2": "Intelligence",
    "blogPage.description": "Your definitive resource for in-depth technical articles on cargo protection, moisture management, and safe shipping practices—backed by 45+ years of Danish engineering expertise.",
    "blogPage.tag1": "Desiccant science",
    "blogPage.tag2": "Container climate",
    "blogPage.tag3": "Moisture prevention",
    "blogPage.tag4": "Best practices",
    "blogPage.feature1.title": "Scientific analysis",
    "blogPage.feature1.desc": "Deep dives into moisture control chemistry and material science",
    "blogPage.feature2.title": "Protection strategies",
    "blogPage.feature2.desc": "Proven methods to safeguard cargo across all transport modes",
    "blogPage.feature3.title": "Industry trends",
    "blogPage.feature3.desc": "Latest developments in logistics and cargo preservation",
    "blogPage.latestArticles": "Latest articles",
    "blogPage.latestDesc": "Technical insights from our moisture control experts",
    "blogPage.ctaTitle": "Need expert guidance?",
    "blogPage.ctaDesc": "Our technical team is ready to help you design the optimal moisture protection strategy for your specific cargo requirements.",
    "blogPage.ctaButton": "Consult our experts",
    "blogPage.backToBlog": "Back to Cargo Intelligence",
    "blogPage.share": "Share",
    "blogPage.moreArticles": "More articles coming soon to Cargo Intelligence",
    "blogPage.articleNotFound": "Article not found",
    "blogPage.articleNotFoundDesc": "The article you're looking for doesn't exist.",
    "blogPage.backButton": "Back to Cargo Intelligence",
    "blogPage.category.technical": "Technical",
    "blogPage.minRead": "min read",

    // Social Proof Page
    "socialProof.badge": "Customer success",
    "socialProof.title1": "Trusted by industry",
    "socialProof.title2": "leaders worldwide",
    "socialProof.description": "See why leading companies across the globe trust DRY-BAG for their moisture control and cargo protection needs.",
    "socialProof.trustedBy": "Trusted by leading companies",
    "socialProof.reviewsTitle": "What our customers say",
    "socialProof.reviewsSubtitle": "Real feedback from businesses we've helped protect their cargo.",
    "socialProof.videoTitle": "Video testimonials",
    "socialProof.videoSubtitle": "Hear directly from our customers about their experience with DRY-BAG.",
    "socialProof.ctaTitle": "Ready to protect your cargo?",
    "socialProof.ctaDesc": "Join thousands of satisfied customers who trust DRY-BAG to keep their products safe during transit.",
    "socialProof.ctaButton": "Get in touch",
    "socialProof.review1.name": "Henrik Larsen",
    "socialProof.review1.role": "Logistics Manager",
    "socialProof.review1.company": "Nordic Shipping Co.",
    "socialProof.review1.text": "DRY-BAG has been instrumental in reducing our moisture-related cargo claims by over 90%. Their expertise and product quality are unmatched in the industry.",
    "socialProof.review2.name": "Maria Schmidt",
    "socialProof.review2.role": "Supply Chain Director",
    "socialProof.review2.company": "EuroMetal GmbH",
    "socialProof.review2.text": "We've been using DRY-BAG products for over a decade. The consistency and reliability of their desiccants have made them an essential part of our shipping process.",
    "socialProof.review3.name": "James Chen",
    "socialProof.review3.role": "Operations Head",
    "socialProof.review3.company": "Pacific Trade Solutions",
    "socialProof.review3.text": "The technical support from DRY-BAG is exceptional. They helped us optimize our moisture control strategy and saved us significant costs on damaged goods.",
    "socialProof.video1.name": "Anna Johansson",
    "socialProof.video1.role": "CEO",
    "socialProof.video1.company": "Scandinavian Exports",
    "socialProof.video2.name": "Peter Williams",
    "socialProof.video2.role": "Quality Manager",
    "socialProof.video2.company": "Atlantic Cargo Ltd.",
    "socialProof.video3.name": "Sophie Martin",
    "socialProof.video3.role": "Procurement Director",
    "socialProof.video3.company": "Continental Foods",
  },
  da: {
    // Navigation
    "nav.about": "Om os",
    "nav.products": "Produkter",
    "nav.applications": "Anvendelser",
    "nav.cargo": "Fragt",
    "nav.blog": "CARGO INTELLIGENCE",
    "nav.contact": "Kontakt",
    "nav.resources": "Ressourcer",
    "nav.getQuote": "Få tilbud",
    "nav.faq": "FAQ",
    "nav.viewAllProducts": "Se alle produkter",
    "nav.desiccants": "Tørremidler",
    "nav.cargoProtection": "Fragtbeskyttelse",
    "nav.otherProducts": "Andre produkter",
    
    // Products
    "products.drybagI": "DRY-BAG I",
    "products.drybagIII": "DRY-BAG III",
    "products.silica": "Silica gel",
    "products.dunnage": "Dunnage bags",
    "products.molecular": "Molekylsigte",
    "products.calcium": "Calciumchlorid",
    "products.retail": "Detailprodukter",
    "products.edge": "Kantbeskyttere",
    "products.antiSlip": "Skridsikre ark",
    "products.stabustrap": "Stabustrap",
    "products.datalogger": "Datalogger",
    
    // Footer
    "footer.company": "Virksomhed",
    "footer.resources": "Ressourcer",
    "footer.downloads": "Downloads",
    "footer.technicalSpecs": "Tekniske specifikationer",
    "footer.caseStudies": "Casestudier",
    "footer.aboutUs": "Om os",
    "footer.industries": "Brancher",
    "footer.privacy": "Privatlivspolitik",
    "footer.terms": "Servicevilkår",
    "footer.rights": "Alle rettigheder forbeholdes.",
    "footer.tagline": "Førende dansk producent af højkvalitets tørremidler, der beskytter fragt verden over siden 1979.",
    
    // Top bar
    "topbar.message": "Dansk ingeniørkunst siden 1979 | Global forsendelse tilgængelig",

    // Hero Section
    "hero.badge": "Brancheførende beskyttelse",
    "hero.title1": "DIN PARTNER INDEN FOR",
    "hero.title2": "FUGTKONTROL",
    "hero.title3": "& FRAGTSIKKERHED",
    "hero.description": "Oplev vores innovative og bæredygtige løsninger til beskyttelse af dine varer mod fugtskader og sikring af stabil transport verden over.",
    "hero.exploreProducts": "Udforsk produkter",
    "hero.contactUs": "Kontakt os",
    "hero.yearsExperience": "Års erfaring",
    "hero.countriesServed": "Lande betjent",
    "hero.globalSupport": "Global support",

    // About Section
    "about.badge": "Om DRY-BAG",
    "about.title1": "Førende dansk producent af",
    "about.title2": "højkvalitets tørremidler",
    "about.description": "DRY-BAG er en førende dansk producent af højkvalitets tørremidler, der er specifikt udviklet til at beskytte dine varer under transport til både eksport og e-handel. Vi forstår det kritiske behov for at beskytte produkter mod fugtskader og sikre, at de ankommer i perfekt stand hver gang.",
    "about.feature1.title": "Beliggende i Danmark",
    "about.feature1.desc": "Hovedkvarter i hjertet af skandinavisk innovation",
    "about.feature2.title": "Siden 1979",
    "about.feature2.desc": "Over fire årtiers ekspertise inden for fugtkontrol",
    "about.feature3.title": "Miljøvenlig produktion",
    "about.feature3.desc": "Bæredygtige praksisser for en grønnere fremtid",
    "about.feature4.title": "Skræddersyede løsninger",
    "about.feature4.desc": "Specialudviklet til dine specifikke behov",
    "about.yearsExcellence": "Års excellence",
    "about.protectingCargo": "Beskytter fragt verden over",

    // Products Section
    "products.badge": "Udvalgte produkter",
    "products.title1": "Industriel",
    "products.title2": "beskyttelsesløsninger",
    "products.description": "Udforsk vores udvalg af innovative løsninger designet til at beskytte dine varer og optimere dine logistikoperationer.",
    "products.viewAll": "Se alle produkter",
    "products.learnMore": "Læs mere",
    "products.dunnageBag.subtitle": "Kraftpapir & PP-vævet",
    "products.dunnageBag.desc": "Industrielle luftposer til stabilisering af fragt under transport",
    "products.drybagI.subtitle": "Original formel",
    "products.drybagI.desc": "Lerbaseret tørremiddel udviklet til lange sørejser",
    "products.silicaGel.subtitle": "E-handelsklart",
    "products.silicaGel.desc": "Premium silica gel-pakker til fugtbeskyttelse i emballage",
    "products.drybagIII.subtitle": "Bentonit ler",
    "products.drybagIII.desc": "Industritørremiddel tilgængeligt i flere størrelser",

    // Industries Section
    "industries.badge": "Anvendelser",
    "industries.title1": "Skræddersyede løsninger til",
    "industries.title2": "enhver branche",
    "industries.description": "Oplev hvordan vores fugtkontrolløsninger beskytter kritiske aktiver på tværs af forskellige brancher verden over.",
    "industries.wind.title": "Vindenergi",
    "industries.wind.desc": "Tørremidler forhindrer fugt i at korrodere kritiske komponenter i vindmøller, såsom gearkasser og generatorer. Ved at opretholde et tørt internt miljø forlænges levetiden og sikres pålidelig drift.",
    "industries.metals.title": "Metalindustri",
    "industries.metals.desc": "Beskyt stålruller, aluminiumsplader og præcisionsmetalkomponenter mod rust og oxidation under forsendelse. Vores løsninger sikrer, at metaller ankommer i upåklageligt stand.",
    "industries.food.title": "Fødevarer & foder",
    "industries.food.desc": "Beskyt fødevareingredienser og dyrefoder mod fugtinduceret fordærv. Vores fødevaresikre tørremidler opretholder produktkvaliteten gennem hele forsyningskæden.",
    "industries.pharma.title": "Lægemidler",
    "industries.pharma.desc": "Farmaceutisk-kvalitets molekylsigte-tørremidler sikrer lægemiddelstabilitet og -effektivitet. Opfyld strenge regulatoriske krav med vores certificerede løsninger.",

    // Contact Section
    "contact.badge": "Kontakt os",
    "contact.title1": "Lad os beskytte din",
    "contact.title2": "fragt sammen",
    "contact.description": "Har du spørgsmål om fugtkontrol eller fragtsikkerhed? Vores team er klar til at hjælpe. Uanset om du har brug for et tilbud, tekniske specifikationer eller vejledning om det rigtige tørremiddel til din forsendelse, svarer vi inden for 24 timer.",
    "contact.whyPartner": "Hvorfor vælge DRY-BAG?",
    "contact.benefit1": "40+ års brancheekspertise",
    "contact.benefit2": "Skræddersyede løsninger til dine unikke behov",
    "contact.benefit3": "Global forsendelse med lokal support",
    "contact.benefit4": "24-timers svargaranti",
    "contact.headquarters": "Danmark (Hovedkvarter)",
    "contact.whatsapp": "WhatsApp tilgængelig",
    "contact.form.fullName": "Fulde navn",
    "contact.form.email": "E-mailadresse",
    "contact.form.company": "Virksomhedsnavn",
    "contact.form.message": "Besked",
    "contact.form.placeholder.name": "Anders Andersen",
    "contact.form.placeholder.email": "anders@virksomhed.dk",
    "contact.form.placeholder.company": "Din Virksomhed A/S",
    "contact.form.placeholder.message": "Fortæl os om dine fugtkontrolbehov...",
    "contact.form.submit": "Send besked",

    // About Page
    "aboutPage.badge": "Om os",
    "aboutPage.title1": "Vores job er at gøre",
    "aboutPage.title2": "dit job lettere.",
    "aboutPage.description": "Det betyder at sikre, at dine produkter ankommer i perfekt stand. Med fire årtiers erfaring har vi lært, at hver forsendelse har sine egne udfordringer.",
    "aboutPage.decadesTitle": "Fire årtiers ekspertise",
    "aboutPage.decadesDesc1": "Vores mission, siden 1979, har været pålideligt og ansvarligt at beskytte produkter mod fugt. Vi tilbyder skræddersyede fugtkontrolløsninger designet til at beskytte dine varer med fokus på langsigtet ydeevne og bæredygtighed.",
    "aboutPage.decadesDesc2": "Som producent med egen produktion har vi direkte kontrol over hele processen. Dette giver os mulighed for at sikre, at hvert produkt opfylder vores strenge kvalitetsstandarder, samtidig med at vi tilbyder de mest konkurrencedygtige priser på markedet.",
    "aboutPage.value1.title": "Bæredygtige løsninger",
    "aboutPage.value1.desc": "Vores produkter er designet med miljøbevidsthed i tankerne. Vi bruger miljøvenlige materialer og bæredygtige processer til at levere effektiv fugtkontrol uden at kompromittere din virksomheds grønne initiativer.",
    "aboutPage.value2.title": "Innovativ teknologi",
    "aboutPage.value2.desc": "Vi udnytter banebrydende teknologi og kontinuerlig forskning til at udvikle løsninger, der er i front af branchen. Vores engagement i innovation sikrer, at dine produkter er beskyttet af den mest avancerede fugtkontrol.",
    "aboutPage.value3.title": "Garanteret produktintegritet",
    "aboutPage.value3.desc": "Med over fire årtiers erfaring ved vi, hvordan man beskytter dine varer. Vi leverer pålidelige, skræddersyede løsninger, der konsekvent overstiger forventningerne og giver dig ro i sindet om, at dine produkter ankommer i perfekt stand.",
    "aboutPage.offerTitle": "Hvad vi tilbyder dig",
    "aboutPage.offer1.title": "Skræddersyede løsninger",
    "aboutPage.offer1.desc": "Vi starter med at forstå dine unikke udfordringer for at opbygge en fugtkontrolstrategi, der fungerer specifikt for dig. Det betyder mindre spild og mere ro i sindet.",
    "aboutPage.offer2.title": "Bevist ydeevne",
    "aboutPage.offer2.desc": "Vores produkter er bakket op af over 40 års ekspertise og engagement i kvalitet. Du kan stole på, at vores løsninger vil præstere pålideligt og beskytte dine varer og din bundlinje.",
    "aboutPage.offer3.title": "Langsigtet bæredygtighed",
    "aboutPage.offer3.desc": "Vi er dedikeret til ansvarlige og bæredygtige praksisser. Vores løsninger er designet til effektivitet og langsigtet ydeevne, der hjælper dig med at reducere spild og minimere din miljøpåvirkning.",
    "aboutPage.offer4.title": "Ekspertsupport",
    "aboutPage.offer4.desc": "Vi er mere end bare en leverandør; vi er din partner. Vores team af eksperter er her for at give vejledning og support hele vejen, så dine produkter er beskyttet uanset hvor de skal hen.",
    "aboutPage.statsTitle": "Vores indflydelse i tal",
    "aboutPage.stat1": "år med beskyttelse af fragt globalt",
    "aboutPage.stat2": "tilfredse kunder siden 1979",
    "aboutPage.stat3": "lande hvor vi beskytter fragt",
    "aboutPage.ctaTitle": "Klar til at lære mere?",
    "aboutPage.ctaDesc": "Vi er altid glade for at diskutere, hvordan Dry-Bag kan opfylde dine specifikke behov. Kontakt vores team i dag.",
    "aboutPage.ctaButton": "Kontakt vores eksperter",

    // Contact Page
    "contactPage.badge": "Kontakt os",
    "contactPage.title1": "Kom i kontakt",
    "contactPage.title2": "med Dry-Bag",
    "contactPage.description": "Vi er klar til at servicere din virksomhed ved at hjælpe dig med at beskytte din fragt. Tøv ikke med at kontakte os—vi ser frem til at høre fra dig.",
    "contactPage.formTitle": "Send os en besked",
    "contactPage.form.name": "Navn",
    "contactPage.form.namePlaceholder": "Dit navn",
    "contactPage.form.emailPlaceholder": "din@email.dk",
    "contactPage.form.messagePlaceholder": "Hvordan kan vi hjælpe dig?",
    "contactPage.form.sending": "Sender...",
    "contactPage.alternativeTitle": "Alternative kontaktmuligheder",
    "contactPage.email": "E-mail",
    "contactPage.phone": "Telefon",
    "contactPage.address": "Adresse",
    "contactPage.hours": "Åbningstider",
    "contactPage.hoursValue": "Man-Fre: 8:00 - 15:00 (CET)",
    "contactPage.followUs": "Følg os",
    "contactPage.distributorTitle": "Bliv distributør",
    "contactPage.distributorDesc": "DRY-BAG® distribueres via vores partnere globalt. Hvis du har spørgsmål eller ønsker at blive distributør, er du velkommen til at kontakte os.",
    "contactPage.messageSent": "Besked sendt!",
    "contactPage.messageConfirm": "Vi vender tilbage til dig hurtigst muligt.",

    // Applications Page
    "applicationsPage.badge": "Brancheløsninger",
    "applicationsPage.title1": "Fugtbeskyttelse",
    "applicationsPage.title2": "til enhver branche",
    "applicationsPage.description": "Oplev hvordan vores industrielle tørremidler giver kritisk beskyttelse mod fugtskader, korrosion og fordærv på tværs af en bred vifte af sektorer.",
    "applicationsPage.gridTitle": "Brancher vi servicerer",
    "applicationsPage.gridDesc": "Vores fugtkontrolløsninger er betroet på tværs af forskellige brancher verden over.",
    "applicationsPage.pharmaceutical.title": "Farmaceutisk",
    "applicationsPage.pharmaceutical.desc": "Fugt kan nedbryde aktive ingredienser og forkorte holdbarhed. Vores tørremidler beskytter den kemiske integritet og effektivitet af lægemidler, tabletter og pulvere.",
    "applicationsPage.electronics.title": "Elektronik & halvledere",
    "applicationsPage.electronics.desc": "Fugt er en førende årsag til korrosion og kortslutninger. Vores tørremidler beskytter følsomme komponenter som kredsløbskort og mikrochips under opbevaring og transport.",
    "applicationsPage.food.title": "Fødevarer & drikkevarer",
    "applicationsPage.food.desc": "Forebyg klumpning, fordærv og mikrobiel vækst i tørre fødevarer. Vores fødevaregodkendte tørremidler opretholder friskhed og forlænger holdbarheden af dine produkter.",
    "applicationsPage.logistics.title": "Logistik & forsendelse",
    "applicationsPage.logistics.desc": "Beskyt fragt mod \"containerregn\" og fugtskader under global transport. Vores tørremidler sikrer, at varer ankommer i perfekt stand uanset klimaændringer.",
    "applicationsPage.automotive.title": "Bilindustri",
    "applicationsPage.automotive.desc": "Forebyg korrosion og funktionsfejl i følsom bilelektronik og præcisionsmetaldele. Vores løsninger holder komponenter tørre under opbevaring og transport.",
    "applicationsPage.defense.title": "Forsvar & militær",
    "applicationsPage.defense.desc": "Sikr at missionskritisk udstyr, herunder våben, optik og elektronik, forbliver tørt og funktionelt til langtidsopbevaring og brug i barske miljøer.",
    "applicationsPage.chemical.title": "Kemisk & petrokemisk",
    "applicationsPage.chemical.desc": "Afgørende for fjernelse af vand fra industrielle gasstrømme og beskyttelse af fugtfølsomme kemiske stoffer under forarbejdning og opbevaring.",
    "applicationsPage.textile.title": "Tekstil & læder",
    "applicationsPage.textile.desc": "Forebyg skimmel, mug og misfarvning på tøj, fodtøj og lædervarer. Vores tørremidler opretholder produktkvalitet, især under langtidsopbevaring og forsendelse.",
    "applicationsPage.metal.title": "Metalbearbejdning",
    "applicationsPage.metal.desc": "Bekæmp rust og korrosion på metaldele, værktøj og maskiner. Vores tørremidler giver et beskyttende miljø for komponenter under opbevaring og forsendelse.",
    "applicationsPage.ctaTitle": "Find din løsning",
    "applicationsPage.ctaDesc": "Er du usikker på, hvilket produkt der er rigtigt for din branche? Vores eksperter kan hjælpe dig med at vurdere dine krav og anbefale den mest effektive løsning.",
    "applicationsPage.viewProducts": "Se produkter",
    "applicationsPage.contactExperts": "Kontakt eksperter",

    // FAQ Page
    "faqPage.badge": "Support",
    "faqPage.title1": "Ofte stillede",
    "faqPage.title2": "spørgsmål",
    "faqPage.description": "Find svar på almindelige spørgsmål om vores tørremidler, anvendelser og tjenester.",
    "faqPage.q1": "Hvad er et tørremiddel, og hvordan virker det?",
    "faqPage.a1": "Et tørremiddel er et hygroskopisk stof, der fremkalder eller opretholder en tilstand af tørhed i sit område. Det absorberer vandmolekyler fra den omgivende luft og reducerer effektivt fugtighedsniveauet. Vores tørremidler bruger materialer som silica gel, ler (Moclay) og calciumchlorid til at beskytte produkter mod fugtskader under opbevaring og forsendelse.",
    "faqPage.q2": "Hvilket tørremiddel er det rigtige til min anvendelse?",
    "faqPage.a2": "Det rigtige tørremiddel afhænger af flere faktorer: typen af varer, der skal beskyttes, fugtniveauer, varighed af nødvendig beskyttelse og regulatoriske krav. Silica gel er ideel til lægemidler og elektronik. Lerbaserede produkter som DRY-BAG I og III er fremragende til containerforsendelse. Calciumchlorid er bedst til tunge, lange søfragter. Kontakt vores eksperter for personlige anbefalinger.",
    "faqPage.q3": "Hvor meget tørremiddel har jeg brug for til min container?",
    "faqPage.a3": "Mængden af tørremiddel afhænger af containerstørrelse, indhold, forventet transporttid og klimaforhold. Som hovedregel kan du til en 20ft container have brug for 8-12 enheder DRY-BAG til standardforsendelser. Til ruter med høj fugtighed eller følsom fragt kan der kræves mere. Vores team kan hjælpe med at beregne de nøjagtige krav til din specifikke situation.",
    "faqPage.q4": "Er jeres tørremidler sikre at bruge med fødevarer?",
    "faqPage.a4": "Ja, vores silica gel og lerbaserede tørremidler (DRY-BAG I og III) er lavet med FDA-godkendte materialer og er sikre til brug i fødevarenære anvendelser. De er ugiftige og kemisk inerte. De bør dog ikke indtages. For specifikke fødevaresikkerhedscertificeringer, kontakt os venligst.",
    "faqPage.q5": "Kan tørremidler regenereres og genbruges?",
    "faqPage.a5": "Nogle af vores tørremidler kan regenereres. DRY BAG Retail er specifikt designet til at være regenererbar—tør simpelthen indholdet i en ovn for at genoprette absorptionskapaciteten. Silica gel kan også regenereres i nogle tilfælde. Lerbaserede forsendelsestørremidler er typisk engangsbrug på grund af deres robuste natur.",
    "faqPage.q6": "Hvad er 'containerregn', og hvordan forhindrer tørremidler det?",
    "faqPage.a6": "Containerregn opstår, når temperaturudsving under forsendelse får fugt i luften inde i en container til at kondensere på containervæggene og loftet og derefter dryppe ned på fragten. Dette kan forårsage skimmel, korrosion og vandskade. Tørremidler absorberer overskydende fugt fra luften og forhindrer kondens i at dannes.",
    "faqPage.q7": "Hvordan skal tørremidler opbevares før brug?",
    "faqPage.a7": "Tørremidler bør opbevares i deres originale, forseglede emballage indtil de er klar til brug. Opbevar dem på et køligt, tørt sted væk fra direkte sollys. Når emballagen er åbnet, bør ubrugte tørremidler forsegles igen i lufttætte beholdere eller poser for at forhindre for tidlig fugtabsorption.",
    "faqPage.q8": "Tilbyder I brugerdefinerede størrelser eller formuleringer?",
    "faqPage.a8": "Ja, vi tilbyder skræddersyede løsninger til specifikke anvendelser. Uanset om du har brug for bestemte størrelser, emballagetyper eller absorptionskapaciteter, kan vores team arbejde sammen med dig om at udvikle en skræddersyet fugtkontrolløsning. Kontakt os for at diskutere dine krav.",
    "faqPage.q9": "Hvilke forsendelsesmuligheder er tilgængelige?",
    "faqPage.a9": "Vi sender globalt og tilbyder forskellige forsendelsesmuligheder afhængigt af ordrestørrelse og hastende karakter. Standardfragt, ekspressforsendelse og bulkcontainerlaster er alle tilgængelige. Kontakt vores salgsteam for specifikke forsendelsestilbud og leveringstider.",
    "faqPage.q10": "Hvordan kan jeg blive distributør?",
    "faqPage.a10": "Vi byder partnerskabsforespørgsler velkommen fra potentielle distributører verden over. Hvis du er interesseret i at blive DRY-BAG-distributør, kontakt os venligst med oplysninger om din virksomhed, markedsområde og erfaring inden for fugtkontrol- eller emballagebranchen.",
    "faqPage.ctaTitle": "Har du stadig spørgsmål?",
    "faqPage.ctaDesc": "Kan du ikke finde det, du leder efter? Vores team er her for at hjælpe med alle spørgsmål om vores produkter eller tjenester.",
    "faqPage.ctaButton": "Kontakt os",

    // Blog Page
    "blogPage.badge": "Teknisk vidensbank",
    "blogPage.title1": "Cargo",
    "blogPage.title2": "Intelligence",
    "blogPage.description": "Din ultimative ressource til dybdegående tekniske artikler om fragtbeskyttelse, fugtstyring og sikker forsendelsespraksis—bakket op af 45+ års dansk ingeniørekspertise.",
    "blogPage.tag1": "Tørremiddelvidenskab",
    "blogPage.tag2": "Containerklima",
    "blogPage.tag3": "Fugtforebyggelse",
    "blogPage.tag4": "Bedste praksis",
    "blogPage.feature1.title": "Videnskabelig analyse",
    "blogPage.feature1.desc": "Dybdegående undersøgelser af fugtkontrolkemi og materialevidenskab",
    "blogPage.feature2.title": "Beskyttelsesstrategier",
    "blogPage.feature2.desc": "Beviste metoder til at beskytte fragt på tværs af alle transportformer",
    "blogPage.feature3.title": "Branchetendenser",
    "blogPage.feature3.desc": "Seneste udviklinger inden for logistik og fragtbevarelse",
    "blogPage.latestArticles": "Seneste artikler",
    "blogPage.latestDesc": "Tekniske indsigter fra vores fugtkontroleksperter",
    "blogPage.ctaTitle": "Brug for ekspertvejledning?",
    "blogPage.ctaDesc": "Vores tekniske team er klar til at hjælpe dig med at designe den optimale fugtbeskyttelsesstrategi til dine specifikke fragtkrav.",
    "blogPage.ctaButton": "Konsulter vores eksperter",
    "blogPage.backToBlog": "Tilbage til Cargo Intelligence",
    "blogPage.share": "Del",
    "blogPage.moreArticles": "Flere artikler kommer snart til Cargo Intelligence",
    "blogPage.articleNotFound": "Artikel ikke fundet",
    "blogPage.articleNotFoundDesc": "Den artikel, du leder efter, findes ikke.",
    "blogPage.backButton": "Tilbage til Cargo Intelligence",
    "blogPage.category.technical": "Teknisk",
    "blogPage.minRead": "min læsning",

    // Social Proof Page
    "socialProof.badge": "Kundesucces",
    "socialProof.title1": "Betroet af branche-",
    "socialProof.title2": "ledere verden over",
    "socialProof.description": "Se hvorfor førende virksomheder verden over stoler på DRY-BAG til deres fugtkontrol- og fragtbeskyttelsesbehov.",
    "socialProof.trustedBy": "Betroet af førende virksomheder",
    "socialProof.reviewsTitle": "Hvad vores kunder siger",
    "socialProof.reviewsSubtitle": "Ægte feedback fra virksomheder, vi har hjulpet med at beskytte deres fragt.",
    "socialProof.videoTitle": "Video-anmeldelser",
    "socialProof.videoSubtitle": "Hør direkte fra vores kunder om deres oplevelse med DRY-BAG.",
    "socialProof.ctaTitle": "Klar til at beskytte din fragt?",
    "socialProof.ctaDesc": "Slut dig til tusindvis af tilfredse kunder, der stoler på DRY-BAG for at holde deres produkter sikre under transport.",
    "socialProof.ctaButton": "Kom i kontakt",
    "socialProof.review1.name": "Henrik Larsen",
    "socialProof.review1.role": "Logistikchef",
    "socialProof.review1.company": "Nordic Shipping Co.",
    "socialProof.review1.text": "DRY-BAG har været afgørende for at reducere vores fugtrelaterede fragtskader med over 90%. Deres ekspertise og produktkvalitet er uovertruffen i branchen.",
    "socialProof.review2.name": "Maria Schmidt",
    "socialProof.review2.role": "Supply Chain-direktør",
    "socialProof.review2.company": "EuroMetal GmbH",
    "socialProof.review2.text": "Vi har brugt DRY-BAG produkter i over et årti. Konsistensen og pålideligheden af deres tørremidler har gjort dem til en væsentlig del af vores forsendelsesproces.",
    "socialProof.review3.name": "James Chen",
    "socialProof.review3.role": "Driftschef",
    "socialProof.review3.company": "Pacific Trade Solutions",
    "socialProof.review3.text": "Den tekniske support fra DRY-BAG er fremragende. De hjalp os med at optimere vores fugtkontrolstrategi og sparede os betydelige omkostninger på beskadigede varer.",
    "socialProof.video1.name": "Anna Johansson",
    "socialProof.video1.role": "CEO",
    "socialProof.video1.company": "Scandinavian Exports",
    "socialProof.video2.name": "Peter Williams",
    "socialProof.video2.role": "Kvalitetschef",
    "socialProof.video2.company": "Atlantic Cargo Ltd.",
    "socialProof.video3.name": "Sophie Martin",
    "socialProof.video3.role": "Indkøbsdirektør",
    "socialProof.video3.company": "Continental Foods",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>("en");
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem("language");
    if (saved === "en" || saved === "da") {
      setLanguageState(saved);
    }
    setIsInitialized(true);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
